export const NewTaskBundleEs = {
    WRITE_HERE_A_TASK_NAME: "Escribe aquí el nombre de la tarea ✍️",
    WRITE_HERE_A_TASK_DESCRIPTION: "Escribe aquí una descripción para la tarea 📝",
    START_DATE: "Fecha inicio",
    END_DATE: "Fecha fin",
    SAME_DAY: "Mismo día",
    SAVE: "Guardar",
    UPDATE: "Actualizar",
    SAVING_TASK: "Guardando tarea...",
    TASK_SAVED_SUCCESSFULLY: "Tarea guardada correctamente",
    UPDATING_TASK: "Actualizando tarea...",
    TASK_UPDATED_SUCCESSFULLY: "Tarea actualizada correctamente",
    TODAY: "Hoy",
    IMPORTANT: "Importante",
    ACCEPT: "Aceptar",
    NEW_LABEL: "Nueva categoria",
    SELECT_A_CATEGORY : "Selecciona una categoría",
    INSERT_A_TASK_NAME: "Inserta un nombre de tarea",
    RECENT_CATEGORIES : "Recientes"
}