export const TaskBundleEs = {
    THERE_ARE_NO_CATEGORIES_YET: "No hay categorías todavía. 👋🏼",
    CATEGORIES_EXPLANATION: "Las categorías se usan para organizar tus tareas. Aparecerán aquí según vayas creando nuevas.",
    CREATE_YOUR_FIRST_TASK: "Crea tu primera tarea!",
    NO_TASKS_FOUND : "No se encontraron tareas",
    ALL_TASKS_COMPLETED: "Enhorabuena, has completado todas las tareas",
    TASK_DELETED_SUCCESSFULLY: "Tarea eliminada con éxito",
    TODAY : "hoy",
    TOMORROW : "mañana",
    YESTERDAY : "ayer",
    NOW: "ahora",
    OTHERS: "Sin categoria",
    COMPLETED: "Completadas",
    TASK_ASSIGNED_TO: "Tarea asignada a $1",
    YOU: "ti",
}