export var HTTPS_METHOD;
(function (HTTPS_METHOD) {
    HTTPS_METHOD["GET"] = "GET";
    HTTPS_METHOD["POST"] = "POST";
    HTTPS_METHOD["PUT"] = "PUT";
    HTTPS_METHOD["DELETE"] = "DELETE";
    HTTPS_METHOD["PATCH"] = "PATCH";
    HTTPS_METHOD["HEAD"] = "HEAD";
    HTTPS_METHOD["OPTIONS"] = "OPTIONS";
    HTTPS_METHOD["CONNECT"] = "CONNECT";
    HTTPS_METHOD["TRACE"] = "TRACE";
    HTTPS_METHOD["ALL"] = "ALL";
})(HTTPS_METHOD || (HTTPS_METHOD = {}));
