export const NewTaskBundleEn = {
    WRITE_HERE_A_TASK_NAME: "Write here a task name ✍️",
    WRITE_HERE_A_TASK_DESCRIPTION: "Write here a task description 📝",
    START_DATE: "Start date",
    END_DATE: "End date",
    SAME_DAY: "Same day",
    SAVE: "Save",
    UPDATE: "Update",
    SAVING_TASK: "Saving task...",
    TASK_SAVED_SUCCESSFULLY: "Task saved succesfully",
    UPDATING_TASK: "Updating task...",
    TASK_UPDATED_SUCCESSFULLY: "Task updated succesfully",
    TODAY: "Today",
    IMPORTANT: "Important",
    ACCEPT: "Accept",
    NEW_LABEL: "New category",
    SELECT_A_CATEGORY : "Select a category",
    INSERT_A_TASK_NAME: "Insert a task name",
    RECENT_CATEGORIES : "Recent categories",
}