export const TaskBundleEn = {
    THERE_ARE_NO_CATEGORIES_YET: "There are no categories yet. 👋🏼",
    CATEGORIES_EXPLANATION: "Categories are used to organize your tasks. They will appear here when you create new tasks.",
    CREATE_YOUR_FIRST_TASK: "Create your first one below!",
    NO_TASKS_FOUND : "No tasks found",
    ALL_TASKS_COMPLETED: "Congratulations, you've completed all your tasks",
    TASK_DELETED_SUCCESSFULLY: "Task deleted succesfully",
    TODAY : "today",
    TOMORROW : "tomorrow",
    YESTERDAY : "yesterday",
    NOW: "now",
    OTHERS: "No category",
    COMPLETED: "Completed",
    TASK_ASSIGNED_TO: "Task assigned to $1",
    YOU: "you",
}