name: Publish Release
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm install
    - name : version
      run: echo "::set-output name=version::$(node version.js)" 
      id: version
 
    - name: Install windows dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo apt install software-properties-common
        sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
        wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
        sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
        sudo apt update
        sudo apt-get install -y --install-recommends winehq-devel
        sudo apt-get install -y fakeroot

    - name: Create binaries
      run: npm run update

    - name: Create a Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: "latest"
        prerelease: true
        title: ${{ steps.version.outputs.version }}-${{ github.sha }}
        files: |
          LICENSE
          *.exe
          *.appImage



