name: Publish release
on:
  push:
    branches: [ dev ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - run: npm install

      - name : version
        run: echo "::set-output name=version::$(node version.js)" 
        id: version
 
      - name: Change to production mode
        run: npm run prod

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ steps.version.outputs.version }}-${{ github.sha }}
          build_script_name: dist-${{ matrix.os }}


      - name: Create a Release of commit
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: dev-${{ matrix.os }}
          prerelease: true
          title: dev-${{ matrix.os }}
          files: |
            LICENSE
            dist/*.exe
            dist/*.AppImage