name: Publish Release
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm install
    - name : version
      run: echo "::set-output name=version::$(node version.js)" 
      id: version
 
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        title: ${{ steps.version.outputs.version }}-${{ github.sha }}
        prerelease: true





